server:
  port: 9000
  
spring:
  application:
    name: first-eureka-invoker

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/